### ISSUE TITLE
Break-down the "About page" into separate pages

### ISSUE THREAD

**Issue by flavioazevedo** [forrtproject/forrt#21]
Please break-down the "About page" into separate pages. 

Currently there is one page: https://forrt.org/about/ which has 3 sections: 

https://forrt.org/about/  (this is just "About" content)
https://forrt.org/forrt/#advocacy
https://forrt.org/about/#get-involved 

The request was made so that these are different pages - not one page because it gets very long.

**Comment by SamGuay** [comment]
Where would you put the people, in the about page or get involved or else where?

**Comment by SamGuay** [comment]
I divided the about page as requested. Does Get involved need its own section though? I'd put it with the community/people section? 

On a side note, I would highly suggest that we shorten the [mission section](https://forrt.org/about/mission).
I'll open another issue, but we should have a one-sentence mission at the top, then a couple of aims/goals.

**Comment by flavioazevedo** [comment]
It is looking great Sam! Thanks for this!

Duly noted about the Mission (we are working on it right now on the G-docs https://docs.google.com/document/d/17_eqrVr7X8GWbF7DsSRWGpqU2nuqKlXgXQHepgwXtNc/edit?usp=sharing

You can certainly suggest that there so people follow up with you.

**Comment by SamGuay** [comment]
Thanks. I'll close this for now, but if anything to be changed on the about section, feel free to reopen *this* issue!
