### ISSUE TITLE
Ensure Website Meets Accessibility Standards

### ISSUE THREAD

**Issue by CNSYoung** [forrtproject/forrt#8]
- [x] Ensure all images have alt text

- [ ] Ensure all forms have labels

- [ ] Ensure all contrast errors are fixed

- [ ] Double check heading levels

For reference: https://wave.webaim.org/report#/https://openyour.science/

**Comment by SamGuay** [comment]
I love the report! I didn't know about this tool! Really useful. 


> Ensure all images have alt text

I'll work on this. This *shouldn't* be too hard to find a solution.

> Ensure all forms have labels

There won't be many forms, so we'll make sure to make them accessible. There will be the newsletter one and that's it I think?

> Ensure all contrast errors are fixed

An easy fix for all contrasts error would be to make a choice on our visual identity (color-wise). 
If one is willing to try and find a good contrasting color with @flavioazevedo's beige (#fefdf6) with the  http://colorsafe.co/ tool. I tried a bit, but with the beige, it's not that easy to find a "AAA Goal ratio" color that fits with the beige and the logo. 

My question/solution: How much is Flavio married to the beige? :roll_eyes: 

> Double-check heading levels

This will be tricky, but I can modify the widget generation code to make sure we have H2 and not H1 all over the place!

**Comment by flavioazevedo** [comment]
From my understanding, a lot of the contrast errors are on links (we can definitely use another color for them. I also would love if when hovering the mouse, it changed colors. Before it was light green and hoving pink. But those can certainly change.

**Comment by SamGuay** [comment]
Yes, if you want to try different things and visualize the changes locally, go inside the `data/themes/forrt.toml`. 

![image](https://user-images.githubusercontent.com/30598330/75370328-eb0a1f00-5892-11ea-8194-798790a7ba82.png)
